services:
  backend:
    build:
      context: .
      dockerfile: example-python/Dockerfile
    env_file:
      - example-python/.env
    ports:
      - "8006:8006"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: example-nuxt/Dockerfile
    depends_on:
      - backend
    ports:
      - "3009:3009"
    restart: unless-stopped
